### ISSUE TITLE
Dark Mode Switcher giving error

### ISSUE THREAD

**Issue by danshallcross** [rei-suzuki/figma-dark-mode-switcher#11]
Hi Rei!
My colleague and I are super excited to use this plugin. It works well for my colleague but when I try it I get an error that says:
Failed to import style by key "_string of numbers_".

Can you advise on how to fix this?
Thanks!

**Comment by rei-suzuki** [comment]
@danshallcross Hi Dan!
Thank you for asking! I'm glad you used it with your colleagues.

Did you get this error when you tried to change the color registered in the Design System file?
From the error, it looks like the plugin is not able to load the color style of the Design System file.
In order to change the colors in the Design System file, one step is required, so please try the following method.

```
1. Open your DesignSystem edit page which has defined colors
2. Choose 'Dark Mode Switcher' → 'Save colorStyles from Team Library'
3.Return to the file, Select Frame, then choose 'Dark Mode Switcher' → 'Dark mode' / 'Elevated Dark mode' / 'Light mode'.
```
Let me know if it doesn't work.

**Comment by danshallcross** [comment]
Hey Rei!
Thanks for getting back to me so fast!
The colors are set in the local styles of the file we're working in. I'm not sure if the plugin is looking for a design system file to map the colors instead of looking locally and therefore throwing that error.
My colleague's plugin is working with the local styles.

**Comment by rei-suzuki** [comment]
@danshallcross Hi! 
Sorry for the late reply.
Thank you for the details.

What is the name of the local style you are setting? 
Take a look at the following items.↓

```
・Do the color styles have a set of `Light` and `Dark` strings in each?
・If the name is separated by `/`, it will not work if there is a space before or after the `/`.

For example: `Background/Dark/Primary` 👉 `Background/Light/Primary`
```

Or, you can share the file URL of only the colors with local styles and I'll take a look at the file and see what I can find out.

**Comment by 7thal** [comment]
Hi @rei-suzuki , I'm getting the same error using Figma Desktop App release 93. I set up a new blank file with only two color styles in it:
Background/Light/Primary
Background/Dark/Primary
If I click on the frame with the light color style applied, then choose 'Dark Mode Switcher' - 'Dark Mode' I get the mentioned error above.

**Comment by rei-suzuki** [comment]
@7thal @danshallcross We found a bug when changing the color of a local style after loading a team style. We've fixed it and released to Figma so you can try it out. Thanks for the report!
https://github.com/rei-suzuki/figma-dark-mode-switcher/pull/12
https://www.figma.com/community/plugin/808916768872750785/Dark-Mode-Switcher

**Comment by danshallcross** [comment]
Thanks!! I’ll try it out!

**Comment by 7thal** [comment]
Thank you @rei-suzuki ! It works now! But I get another error on some specific elements instead: "in set_strokeStyleID: Expected "effectStyleID" to have type string but got null instead". What does it mean?

I could narrow it down to one specific element that causes the error but couldn't find anything wrong about it. Also when I remove this element I still get the error if multiple elements are selected (maybe some hidden elements). It would also be nice if the conversion continues anyways, even if there is an error.
